# Site Settings
title               : Air-Legacy
owner               : "Edoardo Mantovani"
## url                : "https://akiritsu.github.io"
## baseurl            : "/pRoJEct-VeXEd"
permalink           : /:title/
description         : "Introduction to Air::Legacy perl library."
markdown            : kramdown

# Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# Collections
collections:
  Suggested_libraries:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
  Reaver_in_Air::Legacy:
    output          : true
    permalink       : /:collection/:title/
  Lorcon2_in_Air::Legacy:
    output          : true
    permalink       : /:collection/:title/
  Cryptography_ in_Air::Legacy:
    output          : true
    permalink       : /:collection/:title/
  Features_in_Air::Legacy:
    output          : true
    permalink       : /:collection/:title/
  
# Social Media Accounts
email               : "Baseband@cpan.org" 
linkedin            : 
github              : "https://github.com/Baseband-processor/Air-Legacy" 
personal github     : "https://github.com/Baseband-processor" 
# website             : 

# Global Variables
statement           : "Designed by DeerRIDER, All Rights Reserved, used by Edoardo Mantovani. All Rights Reserved too"
toc_level           : 3
bgtext              : "ABCFGHKLMNPQRSVWXYZabcdefghijklmnopqrstuvwxyz@#$%&*+-;/[]<>~" # texts randomly displayed in background
# Disqus settings（disqus.com）
# disqus_username     : akiritsu

# Default page configuration
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
  -    
    scope:
      path: ""
      type: notes # file under notes
    values:
      layout: "post"
      tags: n0t3s
      author: aaa
  -    
    scope:
      path: ""
      type: portfolio
    values:
      layout: "post"
      tags: pfl

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Cross-Origin Resource Sharing header
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
