# Site Settings
title               : Air-Legacy
owner               : "Edoardo Mantovani"
## url                : "https://akiritsu.github.io"
## baseurl            : "/pRoJEct-VeXEd"
permalink           : /:title/
description         : "Introduction to Air::Legacy perl library."
markdown            : kramdown

# Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# Collections
collections:
  Suggested_libraries:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Suggested Libraries"
    order:
      - Socket.md
      - Net::Pcap
      - Net::Ncap
      - Net::Frame.md
      - NetPacket.md
      - Net::Write.md
      - Net::Analysis.md
      - Net::Silk.md
      - Net::Inspect.md
      - Net::Tshark.md
      - Net::Sharktools.md
      - File::PCAP.md
      - Net::P0f.md
      - Net::Pcap::Reassemble.md
      - Nagios::NRPE.md
      - Monitoring::Plugin.md
      - Net::Connection::Sniffer.md
      - Net::ARP.md
      - SNMPMonitor.md
      - Net::LibNIDS.md
      - Parse::Snort.md
      - Linux::TunTap.md
  Reaver_Functions:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Reaver in Air::Legacy"
  Lorcon2_Functions:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Lorcon2 in Air::Legacy"
  Cryptography_Functions:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Cryptograpy in Air::Legacy"
  Other_Features    :
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Features in Air::Legacy"
  FaQ               :
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Frequently Asked Questions"

# Social Media Accounts
email               : "Baseband@cpan.org" 
linkedin            : 
github              : "Baseband-processor/" 
# website             : 

# Global Variables
statement           : "Designed by DeerRIDER, All Rights Reserved, used by Edoardo Mantovani. All Rights Reserved too"
toc_level           : 4
bgtext              : "0123456789ABCFGHKLMNPQRSVWXYZabcdefghijklmnopqrstuvwxyz@#$%&*+-;/[]<>~=" # texts randomly displayed in background
# Disqus settings（disqus.com）
# disqus_username     : akiritsu
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Cross-Origin Resource Sharing header
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
