# Site Settings
title               : Air-Legacy
owner               : "Edoardo Mantovani"
## url                : "https://akiritsu.github.io"
## baseurl            : "/pRoJEct-VeXEd"
permalink           : /:title/
description         : "Introduction to Air::Legacy perl library."
markdown            : kramdown

# Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# Collections
collections:
  Aa:
    output          : true
    permalink       : /:collection/:title/
    alias           : "AirPwn in Air::Legacy"
  Bb:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Lorcon2 in Air::Legacy"
  Cc:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Airpcap in Air::Legacy"
  Dd:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Reaver in Air::Legacy"
  Ee:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Formal methods in Air::Legacy"
  Gg:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Aircrack-ng in Air::Legacy"
  Hh:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Cryptology in Air::Legacy"
  Ii:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Fuzzing in Air::Legacy"
  Jj:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
    alias           : "Suggested perl libraries"
  Ll:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Frequently Asked Questions"
  Kk:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Air::Legacy updates"
  Nn:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Download"
  Oo: 
    output          : true
    permalink       : /:collection/:title/
    alias           : "Plans for the future"
  Zz:
    output          : true
    permalink       : /:collection/:title/
    alias           : "About the Authors"
 
# Social Media Accounts
email               : "Baseband@cpan.org" 
linkedin            : 
github              : "Baseband-processor/" 
# website             : 

# Global Variables
statement           : "Designed by DeerRIDER, All Rights Reserved, used by Edoardo Mantovani. All Rights Reserved too"
toc_level           : 6
bgtext              : "01010101010101001001010100101" # texts randomly displayed in background
# Disqus settings（disqus.com）
# disqus_username     : akiritsu
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Cross-Origin Resource Sharing header
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
